### ISSUE TITLE
async branch: GAE API usage emits this error: "There is no active request context for this API call."

### ISSUE THREAD

**Issue by ludoch** [GoogleCloudPlatform/appengine-java-vm-runtime#153]

**Comment by ludoch** [comment]
Now, with the async latest work, API calls can be done with the wrong ticket that we get from the first request, but that may not be valid for other async requests....
The solution is to ignore the first ticket that we get from the request header, and instead, uses the locally calculated ticket (For background threads) that works all the time.

Fix pending.

**Comment by gregw** [comment]
@ludoch while using the globally calculated longappid rather than the specific request ticket should work, I'd just like to understand a bit more about why this is needed, as I can't see how it is related to async per se.

Rather than the async handling, is it that we have gotten rid of the delayed commit handling, thus a response may be flushed/committed before request handling is complete (either synchronously or asynchronously), and that once the response headers have been sent, then the request ticket is no longer valid?

If this is the case, then we could possibly use two request specific environments, one prior to commit using the ticket and one post commit using the appid-  However that would be a little complex and we'd have to be careful of races, so I'd only recommend if there was a good operational reason for using the request ticket.

Is an image with this change available yet on gcr.io ? as I would like to see if it has any effect on #164

**Comment by ludoch** [comment]
Hi

On Feb 11, 2016 01:19, "Greg Wilkins" <notifications@github.com> wrote:
>
> @ludoch while using the globally calculated longappid rather than the
specific request ticket should work, I'd just like to understand a bit more
about why this is needed, as I can't see how it is related to async per se.
>
> Rather than the async handling, is it that we have gotten rid of the
delayed commit handling, thus a response may be flushed/committed before
request handling is complete (either synchronously or asynchronously), and
that once the response headers have been sent, then the request ticket is
no longer valid?
>
> If this is the case, then we could possibly use two request specific
environments, one prior to commit using the ticket and one post commit
using the appid- However that would be a little complex and we'd have to be
careful of races, so I'd only recommend if there was a good operational
reason for using the request ticket.
>
> Is an image with this change available yet on gcr.io ? as I would like to
see if it has any effect on #164
>
Which change are you taking about?
The change that has the use of global ticket is in the async branch, and the
gcr.io tag for it is not latest, but

gcr.io/google_appengine/jetty9-compat:githubheadasync

**Comment by ludoch** [comment]
Note: my fix triggering this issue #153 is  https://github.com/GoogleCloudPlatform/appengine-java-vm-runtime/commit/daffc7f43692e1eb75320672022c440246f4d017 and in the fix branch, not yet un the async branch.
The image that contains this fix triggering the issue is gcr.io/google_appengine/jetty9-compat:githubheadasync (even it is not the async head:-(

**Comment by ludoch** [comment]
Ignore my last comment. async-branch is up to date and gcr.io/google_appengine/jetty9-compat:githubheadasync as well

**Comment by ludoch** [comment]
An experiment we can try is to apply (locally) my fix https://github.com/GoogleCloudPlatform/appengine-java-vm-runtime/commit/daffc7f43692e1eb75320672022c440246f4d017  in head, push a temp image and see if in the master branch which is currently working (no async work at all), the global API ticket is really the issue on the server side

**Comment by ludoch** [comment]
Fixed. in async branch
