### ISSUE TITLE
Provide alternate request ticket behaviours

### ISSUE THREAD

**Issue by gregw** [GoogleCloudPlatform/appengine-java-vm-runtime#230]
Currently the async-support branch installs a [HttpOutput.Interceptor](https://github.com/GoogleCloudPlatform/appengine-java-vm-runtime/blob/async-support/jetty9-compat-base/src/main/java/com/google/apphosting/vmruntime/jetty9/VmRuntimeWebAppContext.java#L362-L380)  that clears the request ticket as the response is committed.

This behaviour should be made configurable, as the request ticket may remain valid while the response is being written.

Furthermore, an configuration option could be provided to mimic the buffering behaviour of the master branch by buffer content here and only flushing when the full request lifecycle is complete.

**Comment by aozarov** [comment]
For synchronous calls is it guaranteed that the `Interceptor.write` callback is only going to be called once at the end of the method? Otherwise shouldn't it consider the `complete` param or is that the reason you were suggesting to mimic the buffering behavior of the master branch?

Do we still think that using the request ticket performs better than using the global ticket?
Speaking with the VM people they think they should have the same performance characteristics and if
that is true. /cc @ludoch

**Comment by gregw** [comment]
The interceptor write method will be called every time the application does a flush OR writes enough data to fill up the aggregation buffer inside our HttpOutput class.   Thus the first write is seen as the commit.      A write with complete==true will always be done, even if it is with an empty buffer (used by a close), so that can indicate the end of writing, but as that could be an explicit close done by either a synchronous or async servlet, it is still possible for API calls to be made after the complete==true write.

API calls can theoretically continue to be made for sync calls until the `request destroyed` listener callback or for async calls until the `AsyncContext.onComplete` callback.

Even if performance is the same between global and request ticket, it is desirable if we can use the request ticket so that trace and logging show the APIs correctly associated with a request.
