### ISSUE TITLE
We should evaluate what would be the best G.C policy for Jetty

### ISSUE THREAD

**Issue by aozarov** [GoogleCloudPlatform/appengine-java-vm-runtime#248]

**Comment by sbordet** [comment]
G1 is going to become the standard in JDK 9. 

It is heavily developed and improved in JDK 8 as well (the main development happens in 9, with backports to 8).

G1 behaves typically well in its default configuration, so it's probably what I would start with.

Having said that, GC tuning is heavily dependent on the application allocation profile and memory usage, so it could be that one size does not fit all, but that can only be known on a case-by-case.

I would start with:

```
-XX:+UseG1GC -Xloggc:<log_file> -XX:+PrintGCDateStamps -XX:+PrintGCDetails -XX:+ParallelRefProcEnabled
```

If you need GC pauses different from 250 ms (the default), you can add:

```
-XX:MaxGCPauseMillis=<pause>
```

In addition to these, other useful options that I always add are:

```
-showversion -XX:+PrintCommandLineFlags
```

These will print in the GC log file the Java version and the extended list of flags that the JVM detects at startup, so that in the log file one can know exactly how the JVM was started.

The JVM supports GC log files rotation, if that is needed, via flags:

```
-XX:+UseGCLogFileRotation -XX:GCLogFileSize=<bytes> -XX:NumberOfGCLogFiles=<number> 
```

**Comment by janbartel** [comment]
Looks like this may be a duplicate of #243, but Simone's info on this one is useful. I'll crossreference.

**Comment by aozarov** [comment]
closing as a duplicate of #243
