### ISSUE TITLE
waring at boot time: WARNING: System properties and/or JVM args set.  Consider using --dry-run or --exec

### ISSUE THREAD

**Issue by ludoch** [GoogleCloudPlatform/appengine-java-vm-runtime#26]
We have this warning:
WARNING: System properties and/or JVM args set.  Consider using --dry-run or --exec
via the local SDK execution in local mode (not docker mode)

The script we use is 
java   -Dgcloud.java.application=xxx -Djetty.home=xxx -Djetty.base=zzz -jar ...../start.jar -module=http -jetty.port=cccc

**Comment by janbartel** [comment]
This warning is because of the incorrect arg "-module=http".  It should be "--module=http". However, looking at the start.ini found in platform/google_appengine/google/appengine/jettybasesdk, the http module is already enabled, so this arg should not be needed on the command line.  

Also, I think the "-jetty.port"=cccc is a typo in raising this bug. I've checked the generated command line and it uses the correct format "jetty.port=cccc" (ie there should be no leading '-' as this is overriding a jetty property, not a system property).

**Comment by ludoch** [comment]
I did a fix in the Cloud SDK... Should be in the GAE 1.9.27 release (Septemberish).
