### ISSUE TITLE
No longer need jetty alpn-boot or ALPN_ENABLE on JVM

### ISSUE THREAD

**Issue by lesv** [GoogleCloudPlatform/appengine-java-vm-runtime#280]
In talking w/ @ludoch (and friends), we realized that with Netty TCNative, we no longer needed ALPN to be involved.  It can be removed.

**Comment by gregw** [comment]
This was also provided in case of a future HTTP2 support.  However I see that now as very unlikely to be supported in the near future, and if eventually supported would probably be h2c rather than h2.  Also we now support ALPN directly in jdk9, which may arrive before any h2 support anyway.  Will remove soon.
