### ISSUE TITLE
Create a Pure Jetty9/Java8 Docker image that is blessed by Google GAE Managed VM

### ISSUE THREAD

**Issue by ludoch** [GoogleCloudPlatform/appengine-java-vm-runtime#37]
The current Docker image we have is for supporting App Engine V1 APIs in a compatibility mode.

We also want a pristine pure Jetty9 Docker image that does not include/support the V1 APIs.
This new image may in the future support session management via the Cloud Datastore, as an option.
I think there are images with Jetty9, but the Cloud Platform wants a blessed supported image, and it is better if we control what it depends on and when we want to upgrade it for whatever security issue or other customer escalation.

**Comment by gregw** [comment]
We can make a docker image with a Jetty home and a minimal base, plus all the start scripts.

I think that the GAE image should then extend this image, adding it's own base and perhaps using the /etc/default/jetty to augment the environment rather than create its own start script... although the standard release start script doesn't yet support generated quickstart script.... but we can fix that.

**Comment by ludoch** [comment]
Yes, we are still design a runtime contract with some rules to make it more
GCE friendly with other layers. For example, the log location so that it
can be consumed automatically in the Cloud console, Cloud Debugger optional
set up, health check contract etc....

I hope we can share this soon, and we can build on it (and adapt it), so
that this pure Jetty9 image has all the bells and whistles of the GCE
platform.

**Comment by ludoch** [comment]
We have now a working Jetty9 image. Should we close this one, and follow up when needed on separate fine tuning bugs?

**Comment by gregw** [comment]
Yep. Closing
