### ISSUE TITLE
Investigate merging all Docker images into 

### ISSUE THREAD

**Issue by ludoch** [GoogleCloudPlatform/appengine-java-vm-runtime#65]
PMs would like to see if we could do 1 single Docker image for Java, that could be simply configured to configure/run a pay load supporting pure Open JDK8 apps (jar), pure Jetty9 Web Apps, and Jetty9 compat mode.

Detection of what to run could be automatic (i.e 

- if there is a jar in /app area, this is a pure JVM run taking JAVA_OPTs settings.

- if there is a Web App we would need extra configuration (default would be pure Jetty9) to either use Jetty9 or Jetty9-compat mode.

Later one, (Crazy ideas), we could add in this generic Java image either the Tomcat8 bits (or get them from from GCS bucket) and have a simple extra configuration to use it...

It is something that would be easy to maintain/build/test/configure? It is something that will make developers happy?
The whole idea is to minimize user configuration (1 single keyword) and still provides a variety of Java support for GAE V2...

**Comment by gregw** [comment]
The gce-debian-openjdk8 is already a java image that can be confgured to run arbitrary java applications.     That image should be customized to further support gce features such as cloud debugger.

However, there is an issue with loading more common functionality into a single image.  For example it would be attractive to preload the jars from appengine-managed-runtime so that they can be used by any container or java application.   However the issue then is what location should they be loaded into, as each container/application has its own conventions as to where common libraries should be located.   /usr/local/jetty/lib/gae/*.jar vs /usr/local/undertow/lib/gae*.jar  etc.

Potentially these jars could be loaded into a common location like /usr/local/share/lib/java/gae/*.jar  and jetty is certainly capable of importing jars from such external locations, but I can't talk to capabilities of other containers, but it may still be desirable.

Thus we could have an image hierarchy like:

gce-debian-openjdk8 - JVM, /usr/local/share/lib/java/gce/*.jar, cloud debugger
gae-debian-openjdk8 - gce-debian-openjdk8 + /usr/local/share/lib/gae/appengine-managed-runtime-*.jar
gae-XYZ - gae-debian-openjdk8 + XYZ app/container

For jetty, we could simply modify the gae.mod module to include those external libraries 

However, I can't see an image that can switch between containers with just a single configuration. That would need to have all the possible containers loaded into it and would thus waste space and time as the image is instantiated.

Note that with docker it is trivial to add jars and change entry points as you create a derived image, so there is very little need to preload potentially unused jars.

**Comment by jboynes** [comment]
Is there any input from users that they want it to work that way rather than how Docker does it with more specialized images as needed (e.g. tomcat -> java -> debian or drupal -> php -> debian)

Agree with gregw@ that packing so many servers into a single image will add bloat and confusion. How would the image decide between Jetty, Tomcat, Wildfly, etc. when trying to run a user's war? What's the policy for adding other server's codebases into that image, or are those all intended to be custom images based on bare debian?

We could just release a basic openjdk image and a set of libraries for users to integrate themselves (i.e. they install whatever they need on the client side and the image gets built from that directory structure).

**Comment by ludoch** [comment]
This is based on a discussion with Google PM folks. Having a debate like
this one will help them refining their position. Same discussion going on
for node.js (for the 80+ different versions!) or python.
No opinion yet, except the current best practice seen in Docker hub that is
n favor or single image per runtime type and multiple tags for versioning.

**Comment by jboynes** [comment]
Do you have examples of this "best practice" - the tomcat -> java -> debian and drupal -> php -> debian don't seem to fit that model. We're not referring to different versions of the same image but totally different types of image (e.g. "debian" provides an OS, "php" provides an interpret + support, "drupal" provides an application framework - debian/openjdk/tomcat is a similar difference).

**Comment by gregw** [comment]
@jboynes I guess the best exemplar of best practise are the [official docker images](https://github.com/appropriate) themselves.   There is no attempt made there to make a taxonomy of application containers - ie there is no docker-webapplication or docker-servletcontainer or docker-jee abstraction.

They have an image hierarchy  of os -> JVM -> Container -> Application

I think it would be very hard to create an image that supported multiple containers.  Even if you restrict yourself to servlet containers there is not full portability between jetty, resin, tomcat, glassfish, tomee, jboss, undertow - with each container having different default profiles supported and there are portability issues between them.    Plus how do you decide which containers will be supported in such a single image as there are many more servlet implementations in part or full. How would a version change from servlet 3.1 to 4.0 be handled if all containers do not upgrade at the same time?

For GCE, I think it makes sense to following the docker official images is best and images can be provided for each container - based of a common gce-debian-openjdk image that includes as much common functionality as possible.  This is perfect for users that do care about what container they use and they can then pick gce-netty / gce-undertow / gce-tomcat  etc as seen fit.    Hopefully if each of the maintainer of those images does their job correctly, these will all be able to use cloud debugging and easy access to other google services as need be (eg the gce-jetty image will soon have a gcloud-datastore based session manager available).

But for GAE, I think it is best to continue with the current practise of hiding the specific implementations that is used.  So the gae-java (perhaps better renamed to gae-servlet) image would initially be built using jetty and expose servlet standard APIs.   If at some stage it proves that tomcat/tomee/undertow etc is a better choice for the officially supported image, then jetty can be swapped out and you have to hope the servlet EG have got their portability right so applications will hardly notice the difference.   Thus users who don't care about which container is used will be able to just use gae-servlet and get all the goodness that is baked in there.

Trying to bake in multiple containers in the first place is just asking for all the portability pain when there is actually no pressing need for it that I can see.   The only way that you could guarantee that the container could be switched arbitrarily with a single configuration value would be to screw down the APIs to the lowest common denominator and stay well away from any modern features that may not be commonly available on all containers.... which I thought is exactly the kind of restriction that GAEv2 is meant to avoid?

**Comment by jboynes** [comment]
@gregw totally confused here. I'm with you in thinking Docker's practice is to create images using that type of hierarchy cf. debian -> java -> tomcat, debian -> java -> jetty, debian -> php -> drupal. I was looking for examples of "best practice" that do not that but instead have alternates within the same image.

IOW, Docker are clearly identifying the product that you are getting when you use an image. That seems the most transparent approach.

**Comment by gregw** [comment]
@jboynes I think we are in agreement then.   Perhaps @ludoch can clarify what he meant by "image type"

To me, the "type" in the context of GCE is definitely jetty/tomcat/tomee/undertow/vertx etc.

But in GAE, the "type" is currently "java", but I see that it should really be "servlet", as that is the API the developers program to and the actual implementation can be swapped out from under them.   If the "type" in GAE became just jetty/tomcat/tomee/undertow/vertx then I can't see the difference between GAE and GCE

**Comment by jboynes** [comment]
Perhaps GAE and GCE *should* be closer.

**Comment by gregw** [comment]
@jboynes I'm not able to answer that question for Google.     But I would think that there is still significant value in providing an environment where a developer can program just to a virtualized servlet container and not be forced to make a choice of a specific implementation.   Isn't that why GAE was able to attract users away from other GCE-like offerings?

The issue of course is what profile does a virtualized servlet container offer, but evidence is that GAEv1 was successful even though it offered a fossilized not 100%  servlet compliant profile.

So I see value in offering both an official GCE container specific images where each image strives to support simple integration with gcloud features;  plus official GAE virtualised images that strives to stay as close to the current servlet API standard whilst using the gcloud features within those implementations.

**Comment by ludoch** [comment]
Consensus is staying with what we have. 3 images: jdk8, jetty9 and jetty9 compat.
