### ISSUE TITLE
Tests Fail On Clean Checkout

### ISSUE THREAD

**Issue by waprin** [GoogleCloudPlatform/appengine-java-vm-runtime#78]
VmRuntimeJettyAuthTest.testAuth_UntrustedInboundIp:154 expected:<307> but was:<403>
  VmRuntimeJettyAuthTest.testAuth_UntrustedInboundIpWithQuery:165 expected:<307> but was:<403>

**Comment by ludoch** [comment]
Wierd, it is passing on a new Jenkins build I just triggered...

**Comment by gregw** [comment]
See also #73

**Comment by ludoch** [comment]
It seems that it is related to using Java7 instead of Java8 for the tests...

Only with java7 we see:

    SEVERE: Could not get login URL:

    com.google.apphosting.api.ApiProxy$RPCFailedException: The remote RPC
to the application server failed for the call user.CreateLoginURL().

    at
com.google.apphosting.vmruntime.VmApiProxyDelegate.runSyncCall(VmApiProxyDelegate.java:182)

    at
com.google.apphosting.vmruntime.VmApiProxyDelegate.makeApiCall(VmApiProxyDelegate.java:142)

    at
com.google.apphosting.vmruntime.VmApiProxyDelegate.makeSyncCallWithTimeout(VmApiProxyDelegate.java:130)

    at
com.google.apphosting.vmruntime.VmApiProxyDelegate.makeSyncCall(VmApiProxyDelegate.java:119)

    at
com.google.apphosting.vmruntime.VmApiProxyDelegate.makeSyncCall(VmApiProxyDelegate.java:62)

    at com.google.apphosting.api.ApiProxy.makeSyncCall(ApiProxy.java:114)

    at com.google.apphosting.api.ApiProxy.makeSyncCall(ApiProxy.java:66)

    at
com.google.appengine.api.users.UserServiceImpl.makeSyncCall(UserServiceImpl.java:126)

    at
com.google.appengine.api.users.UserServiceImpl.createLoginURL(UserServiceImpl.java:59)

    at
com.google.appengine.api.users.UserServiceImpl.createLoginURL(UserServiceImpl.java:39)

    at
com.google.apphosting.vmruntime.jetty9.AppEngineAuthentication$AppEngineAuthenticator.validateRequest(AppEngineAuthentication.java:231)

    at
org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:512)

    at
org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)

    at
org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)

    at
org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)

    at
org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)

    at
org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)

    at
com.google.apphosting.vmruntime.jetty9.VmRuntimeWebAppContext.doScope(VmRuntimeWebAppContext.java:301)

    at
org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)

    at
org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:215)

    at
org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110)

    at
org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)

    at org.eclipse.jetty.server.Server.handle(Server.java:499)

    at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)

    at
org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)

    at
org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)

    at
org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)

    at
org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)

    at java.lang.Thread.run(Thread.java:745)

**Comment by waprin** [comment]
Yes exactly, things work for me on Java 8. Also strange because the pom file specifies using the Java 7 language. Also, I haven't looked closely at the individual tests, but they don't seem to be running at all on Java 8. With 8 I get 13 success 0 failures, with Java 7 I get 13 successes 2 failures.

**Comment by waprin** [comment]
InetAddress.getLocalHost().getHostAddress() produces 127.0.0.1 on Java 7 but my en0 address ( 172.31.155.212 for me) on Java 8...guessing that's root of the issue. I have seen this before, I think it's this:

http://stackoverflow.com/questions/1881546/inetaddress-getlocalhost-throws-unknownhostexception

**Comment by waprin** [comment]
Ok, I had my hostname mapped to 127.0.0.1 based on this https://groups.google.com/forum/#!topic/h2-database/DuIlTLN5KOo. I switched to my hosts file to point to my hostname en0 interface and it worked.

Either way, the tests don't seem to work on the loopback interface, not sure why. I am also not sure if this is specific to OS X, still need to test on Linux. Not sure if it makes more sense to try to fix the tests on Java 7/OS X or just document the workaround/highly suggest people use Java 8.

**Comment by gregw** [comment]
The issue is that the other tests force the remote IP with
```
    get.addRequestHeader(VmApiProxyEnvironment.REAL_IP_HEADER, "127.0.0.1");
```
and that is considered a trusted IP.

So the tests for untrusted IP only work if the IP used is the unknown local en0 (or wlan0) IP. If the host is mapped to localhost, then it is treated as a trusted IP and the tests fail.

Solution I've just created a PR for is to do:
```
    get.addRequestHeader(VmApiProxyEnvironment.REAL_IP_HEADER, "127.0.0.1");
```
and the code that checks for dev mode knows that this is treated as an untrusted IP
