### ISSUE TITLE
Enable ALPN in openjdk8 image

### ISSUE THREAD

**Issue by gregw** [GoogleCloudPlatform/appengine-java-vm-runtime#82]
Enable ALPN in openjdk9 image as part of the boot classpath of the JVM.   Use this ALPN for HTTP/2 in the pure jetty image and GAEv2 images

**Comment by lesv** [comment]
That's a great idea -- if you do it, remember to add in webapps/root.xml  (or it's equivalent)

```  
<Call name="addSystemClass">
    <Arg type="String">org.eclipse.jetty.alpn.</Arg>
</Call>
  <Set name="parentLoaderPriority">
    <SystemProperty name="jetty_parent_classloader" default="false"/>
</Set>
```
So ALPN can be found by Netty in gRPC.

**Comment by gregw** [comment]
@lesv 
I think it should probably be exposed by default in jetty, so I've created this issue: https://bugs.eclipse.org/bugs/show_bug.cgi?id=477641

**Comment by lesv** [comment]
Probably should, but it's definitely not now.  Thanks -- good idea.

**Comment by gregw** [comment]
There are two ways we can proceed with this.

We are currently working with the openjdk9 developers reviewing their ALPN implementation.   The key thing about the proposed openjdk9 ALPN support is that it is a significantly different model to what we have implemented in the jetty project.  Specifically it has a different callback model that makes the selection of the cipher/protocol/alias an iterative process allowing co-dependencies.

We could just add the existing jetty ALPN to the openjdk8 images and leave the porting to the new model to when things are switched to openjdk9.  

Alternatively, we could do the work now to morph the current jetty image to offer the same API and interaction style as proposed for openjdk9.  This would both test the openjdk9 API (as it really needs real test cases to check) and would mean that newly developed ALPN dependent code would not need to be reworked in a year or two, which may make an impediment for openjdk9 adoption.

As ALPN is "new" in the context of the official google java images, I think consideration should be given to this second approach.

**Comment by gregw** [comment]
@lesv any comment on the openjdk9 API style?

**Comment by lesv** [comment]
I can talk about alpn-jetty interaction in how I use it, but @ejona86 is better equipped to comment.

**Comment by ejona86** [comment]
gRPC Java's 0.9.0 release is now encouraging the use of netty-tcnative that uses OpenSSL instead of Jetty APLN. That gives greater performance in general, _much_ better performance for GCM ([Java's currently gets 1 MB/s](https://bugzilla.redhat.com/show_bug.cgi?id=1135504)), doesn't depend on the precise JDK version, and needs no platform support other than OpenSSL 1.0.1 or later being installed (yes, we accept that we may only get NPN).

When openjdk9 is out with its ALPN support, we'll port gRPC to it. That will likely just be porting Netty to it. Netty exposes [a limited API](https://github.com/netty/netty/blob/master/handler/src/main/java/io/netty/handler/ssl/ApplicationProtocolConfig.java) that I fully expect would be implementable in any ALPN-supporting system. Note that it doesn't require supporting all `SelectorFailureBehavior`s and `SelectedListenerFailureBehavior`s.

If we wanted to start getting real-world usage of the openjdk9 ALPN API, I would suggest we try to integrate the changes into Netty and see how well things work. I've not come across the ALPN API proposed; is there a link to it that I could look at?
